networks:
  lumen:

services:
  lumen:
    build:
      args:
        user: docker
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    # container_name: lumen-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lumen

  db:
    image: mysql:8.0
    # container_name: lumen-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.config/mysql:/docker-entrypoint-initdb.d
    networks:
      - lumen

  nginx:
    image: nginx:alpine
    #container_name: lumen-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.config/nginx:/etc/nginx/conf.d/
    networks:
      - lumen
